### ISSUE TITLE
Config Docker de Testes de Integração

### ISSUE THREAD

**Issue by Felipeness** [devhatt/pet-dex-backend#103]
**Describe the feature**

Esta funcionalidade propõe a criação de um setup de Docker Compose para testes de integração em ambientes de projeto Go, visando facilitar a execução de testes em condições semelhantes às de produção de forma isolada e reproduzível.

<details open>
  <summary>
    <b>Description</b>
  </summary>
   Esta solicitação de funcionalidade envolve a configuração e criação de um setup de Docker Compose para execução de testes de integração em um ambiente de projeto Go (Golang). O objetivo é otimizar o processo de testes permitindo que os desenvolvedores facilmente configurem ambientes de teste isolados que imitam de perto as configurações de produção, assegurando que os testes de integração sejam executados de maneira consistente e controlada através de diferentes configurações de desenvolvimento.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Os testes de integração desempenham um papel crucial no ciclo de vida do desenvolvimento, garantindo que os componentes individuais de um sistema de software funcionem juntos conforme esperado. No contexto de projetos Go, essa funcionalidade beneficia os desenvolvedores fornecendo um ambiente de teste reproduzível e isolado, utilizando contêineres Docker. Essa configuração é particularmente útil para testar interações com serviços externos ou bancos de dados, onde simular condições semelhantes à produção é essencial para resultados de testes precisos. Ela melhora a confiabilidade dos testes, facilita os processos de integração contínua (CI) e suporta práticas de DevOps, permitindo que os desenvolvedores testem alterações localmente em uma configuração que espelha o ambiente de CI, reduzindo o problema de "funciona na minha máquina".
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Para implementar essa funcionalidade, um arquivo docker-compose.yml será criado na raiz do projeto Go. Este arquivo definirá os serviços, redes e volumes necessários para os testes de integração. Componentes chave incluirão:

Serviço Go: Define o contêiner da aplicação, construído a partir de um Dockerfile que configura o ambiente Go e inclui o código do projeto.
Serviços Externos: Contêineres para quaisquer serviços externos com os quais a aplicação interage, como bancos de dados, filas de mensagens ou APIs de terceiros, instâncias simuladas ou reais conforme necessário.
Redes: Redes personalizadas para facilitar a comunicação segura e eficiente entre o contêiner da aplicação Go e os serviços externos.
Volumes: Volumes persistentes para serviços que requerem armazenamento de dados, garantindo que os dados sejam mantidos entre execuções de testes, se necessário.
A configuração do Docker Compose será projetada para ser invocada com um comando simples, como docker-compose up -d --build, para executar os testes de integração, e docker-compose down para desmontar o ambiente após os testes. Adicionalmente, um guia ou script pode ser fornecido para simplificar essas operações para os desenvolvedores.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

Nenhum conceito visual específico é aplicável para esta funcionalidade🐳🐳

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  

</details>

**Comment by efipemux** [comment]
EU QUERO

**Comment by efipemux** [comment]
EU QUERO!!!
