### ISSUE TITLE
Listagem de ONG

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#110]
**Describe the feature**
Essa Issue visa entregar o endpoint de listagem de ongs

<details open>
  <summary>
    <b>Description</b>
  </summary>
    Um endpoint GET que lista as ongs no banco, com paginação, ordenação e com testes unitarios
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Eu como usuario posso listar ongs para poder depois acessar os pets delas.

</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

 - Listagem de ongs no banco
 - Paginação
 - Ordenação por Nome e Endereço Tanto ASC quanto DESC
 - Testes unitarios que verifiquem as funcionalidades

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by DominMFD** [comment]
Eu quero!!!
