### ISSUE TITLE
Consultar ONG

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#111]
**Describe the feature**
Endpoint para trazer informações da ONG

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Endpoint  deve receber um ID e retornar as informações importantes. Esse endpoint não é autenticado.

</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>

  </summary>

Necessário teste unitário.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>
<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>

Ter todo o fluxo de autenticação feito
Ter todo o fluxo de login feito
 
 Esta sendo resolvido no PR abaixo:
https://github.com/devhatt/pet-dex-backend/pull/88
</details>

<br>

**Comment by AtilaRocha** [comment]
EU QUERO !!!

**Comment by AtilaRocha** [comment]
EU QUERO!!!

**Comment by Clerijr** [comment]
eu quero!!!
