### ISSUE TITLE
Update ONG

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#112]
**Describe the feature**
Endpoint para atualizar uma ONG
<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
A função recebe um id e os campos que serão atualizados 
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Essa rota deve ser protegida.
Necessário teste unitário.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>
<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>

Ter todo o fluxo de autenticação feito
Ter todo o fluxo de login feito
 
 Esta sendo resolvido no PR abaixo:
https://github.com/devhatt/pet-dex-backend/pull/88
</details>

<br>

**Comment by Clerijr** [comment]
eu quero!!!
