### ISSUE TITLE
Criar Delete de ONG

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#113]
**Describe the feature**
Essa Issue visa entregar o endpoint de delete de ong

<details open>
  <summary>
    <b>Description</b>
  </summary>
    Um endpoint DELETE que deleta as ongs no banco, usando o conceito de 
[soft delete](https://www.tabnews.com.br/LuC45m4Th3u5/voce-sabe-o-que-e-soft-delete) enquanto estou autenticado.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
  Eu como uma propria ong posso deletar eu mesma.

</details>
<br>
<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>
     
Ter todo o fluxo de autenticação feito
Ter todo o fluxo de login feito
 
 Esta sendo resolvido no PR abaixo:
https://github.com/devhatt/pet-dex-backend/pull/88
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

 - Verificar se a ong é autenticada
 - Deletar usando SoftDelete
 - Implementar testes unitarios

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by klebsonmateus** [comment]
eu quero !!!

**Comment by klebsonmateus** [comment]
eu quero!!!

**Comment by matheus-webp** [comment]
eu quero!!!
