### ISSUE TITLE
Criar Delete de Usuário

### ISSUE THREAD

**Issue by Felipeness** [devhatt/pet-dex-backend#114]
**Describe the feature**

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Implementar uma funcionalidade de exclusão suave (soft delete) para contas de usuários no nosso sistema. Essa funcionalidade deve permitir aos usuários deletar suas contas garantindo que os dados sejam apenas marcados como excluídos no banco de dados, em vez de serem permanentemente removidos. Esse processo deve ser projetado de forma segura para garantir que apenas o proprietário da conta, quando autenticado e logado, possa deletar sua própria conta.
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
Essa funcionalidade é crucial para respeitar a privacidade do usuário e o controle sobre seus dados, permitindo que os usuários se retirem do serviço sempre que escolherem. Ela beneficia o projeto alinhando-se às regulamentações de proteção de dados e melhorando a confiança do usuário. Além disso, ao implementar a exclusão suave, mantemos a flexibilidade de restaurar a conta caso o usuário decida retornar, melhorando assim a experiência do usuário e potencialmente reduzindo a perda de usuários.
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Autenticação: Os usuários devem estar logados para deletar suas contas. Implemente verificações para assegurar que o userId na requisição corresponda ao ID do usuário autenticado.

Lógica de Exclusão: Em vez de remover o registro do usuário do banco de dados, modifique os dados do usuário para marcar a conta como 'deletada'. Isso pode ser uma flag booleana isDeleted ou um timestamp deletedAt.

Considerações de Segurança: Garanta que o processo de exclusão seja seguro e que a autenticação seja robusta para prevenir exclusões de conta não autorizadas.

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Considere pensar em uma implementação de uma funcionalidade de desfazer que permite aos usuários recuperar sua conta dentro de um determinado período após a exclusão. Isso exigiria a retenção temporária dos dados e uma estratégia de comunicação clara sobre quanto tempo os dados serão mantidos antes da exclusão permanente.

</details>

**Comment by davidspader** [comment]
eu quero!!!
