### ISSUE TITLE
Criar referencias visuais para tarefas 

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#116]
**Describe the feature**
Precisamos criar referencias visuais para as tarefas do petdex

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

Atualizar as seguintes tarefas abertas para termos uma melhor visualizacao
- CRUD de Usuarios
- CRUD de BREED
- CRUD de ONG
- CRUD de Usuarios

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
Usar o Scalidraw como ferramenta, segue algumas referencias:
https://github.com/devhatt/pet-dex-backend/issues/32
</details>

**Comment by mmaysc** [comment]
Eu quero!!!

**Comment by mmaysc** [comment]
Referências visuais acerca das [milestones ](https://github.com/devhatt/pet-dex-backend/milestones) de CRUD:


CRUD PET 
- [X] #57 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/6015a3a8-a91a-4759-b9ef-e29d9cf8caa8)

- [X] #55 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/12db550a-e570-4cb0-9203-82812b50eafb)

- [X] #54 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/51a98b37-dbcd-4902-8990-b847d31a2b98)


CRUD BREED
- [X] #128 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/817117cf-f976-42ba-84ff-0faba171cb90)


CRUD USUÁRIO
- [X] #114 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/d85e5250-1d51-4dcf-b0c1-ae8f393f78f4)

-  [ ] #115 

CRUD ONG
- [ ] #40 
- [ ] #111 
- [X] #112  
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/a3462d0c-3edc-438b-97b6-9439383687e6)

- [X] #110 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/08edf275-6e8c-473f-a9f4-c1094e36dc51)

- [X] #113 
![image](https://github.com/devhatt/pet-dex-backend/assets/84260546/c1710ab7-d4d9-4303-8cec-66620b1eed25)





Visualizar [aqui](https://excalidraw.com/#json=_cbaYABLRWOK_OnTz5-4H,roo_hVwSjMFFz24qNAIEdA).



_Observações_: issues com PR aberto foram desconsideradas.

@devlefel
