### ISSUE TITLE
Revisar READ.me do projeto

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#118]
**Describe the feature**
O projeto passou por muitas alterações e hoje em dia o Readme não faz mais jus ao estado atual do projeto

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
Exemplos de problemas: 

- os badges estão todos errados
![image](https://github.com/devhatt/pet-dex-backend/assets/76929097/a19db689-4f20-4e20-bf12-6eb264e84c89)
- o link de convite do discord ta errado tambem
![image](https://github.com/devhatt/pet-dex-backend/assets/76929097/a82d036e-a6e1-46af-9ee5-1093022a6594)

outras coisas necessárias são: como rodar o projeto, linkar guideline, style guide, diretrizes da comunidade

exemplo de readme internos da comunidade: 
https://github.com/devhatt/octopost

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by juliaam** [comment]
Eu quero!!!
