### ISSUE TITLE
Estudar e implementar swagger na aplicação

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#119]
**Describe the feature**
O projeto esta crescendo e precisamos documentar as rotas

<details open>
  <summary>
    <b>Description</b>
  </summary>
Estudar e implementar uma rota documentada com o Swagger ou outra ferramenta de documentação
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
padrão das rotas:  https://github.com/devhatt/pet-dex-backend/issues/82#issuecomment-1965462948
</details>

**Comment by marcos-ab-nolasco** [comment]
Eu quero!

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
