### ISSUE TITLE
[DOC /PET] Documentar rota /api/pets/

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#120]
**Describe the feature**
Documentar as rotas sob o dominio/contexto de /api/pets/         GET

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Documentar o endpoint que retorna a listagem de pets. Incluir detalhes sobre os parâmetros de consulta, formato de resposta, exemplos de uso, e status codes possíveis.
</details>

<br>

<details> 
  <summary>
    <b>Acceptance Criteria</b>
  </summary>
A documentação deve conter uma descrição clara da rota.<br/>
Exemplo de requisição e resposta.<br/>
Explicação dos status codes.<br/>
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>
O swagger está no MakeFiles
Issue:  #119
swag:
	swag init -g api/main.go -o swagger/

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>
<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>

</details>

<br>

**Comment by davidambz** [comment]
essa task foi duplicada, o @EdiltonOliveira fez na issue #179
