### ISSUE TITLE
[DOC pkg] Documentar pacote de email

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#121]
**Describe the feature**
Documentar pacote de email, explicar como implementar e usar o adapter de email

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

o @k1nha fez alguns templates que podem ajudar na documentação https://github.com/devhatt/pet-dex-backend/issues/82#issuecomment-1992724069

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by juliaam** [comment]
Eu quero!!!
