### ISSUE TITLE
Fazer função de Pegar uma unica breed

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#128]
**Describe the feature**
Fazer função de Pegar uma unica breed somente em nivel de service.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  Atualmente precisamos de uma funcionalidade em usecase de breed que busca uma raça no banco de dados dado um ID
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by luanc202** [comment]
Eu quero!!!
