### ISSUE TITLE
[FIX] Corrigir logs nos uses cases e controllers

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#140]
Hoje em dia, temos alguns casos onde o logger não está no padrão pré estabelecido ou não estão implementados. Seria necessário refatorar e implementar

Exemplos:

![image](https://github.com/devhatt/pet-dex-backend/assets/13355406/654e4fb8-1632-4a3c-b108-35b07e471779)

Estado atual em `usecase/pet.go` faltando

![image](https://github.com/devhatt/pet-dex-backend/assets/13355406/aa2d407a-ef6a-4b08-9c60-676cd0d9a3f4)

**Comment by oswaldo-oliveira** [comment]
eu quero!!!
