### ISSUE TITLE
Padronizar testes usando Mockery 

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#147]
**Describe the feature**
Mockery é uma ferramenta para gerar mocks de forma mais simples

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
https://github.com/vektra/mockery
</details>

**Comment by EdiltonOliveira** [comment]
eu quero!!!
