### ISSUE TITLE
Lint pra aplicação na hora do CI

### ISSUE THREAD

**Issue by zoldyzdk** [devhatt/pet-dex-backend#155]
**Describe the feature**
Integrar um lint pra ser executado durante o processo de CI, Lefel recomendou esse: https://golangci-lint.run/.

<details open>
  <summary>
    <b>Description</b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by luanc202** [comment]
Eu quero!!!
