### ISSUE TITLE
Adicionar Rota de Find ID de PET e Documentação

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#168]
**Describe the feature**
Fazer uma rota GET que busque um pet por ID

<details open>
  <summary>
    <b>Atualmente temos toda a logica de negocio e controller de FindByID de Pet, porem não temos uma rota que exponha esse fluxo, nesse caso devemos expor a rota de findByID e tambem adicionar a documentação do swagger.
    O Guia para adicionar a documentacao do Swagger está no guia de contribuicao na raiz do projeto
    </b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
