### ISSUE TITLE
Documentar as rotas sob o domínio/contexto de /api/pets/{petId} PATCH

### ISSUE THREAD

**Issue by Felipeness** [devhatt/pet-dex-backend#175]
**Describe the feature**
Documentar as rotas sob o domínio/contexto de /api/pets/{petId} PATCH

<details open>  
  <summary>  
    <b>Description</b>  
  </summary>  
  Documentar o endpoint que permite atualizar as informações de um pet específico. Incluir detalhes sobre os parâmetros de URL, corpo da requisição, formato de resposta, exemplos de uso, e status codes possíveis.  
</details>  
<br>  
<details>  
  <summary>  
    <b>Acceptance Criteria</b>  
  </summary>  
A documentação deve explicar como utilizar o parâmetro `{petId}`.<br/>  
Estrutura do corpo da requisição e exemplo.<br/>  
Explicação dos status codes.<br/>  
</details>  
<br>  
<details>  
  <summary>  
    <b>Implementation Details</b>  
  </summary>  
Está no MakeFiles  
Issue: #119
swag:  
	swag init -g api/main.go -o swagger/  
</details>  
<br>  
<details>  
  <summary>  
    <b>Visual Concepts</b>  
  </summary>  
[Include any visual representations or concepts if those are available and applicable.]  
</details>  
<br>  
<details>  
  <summary>  
    <b>Additional Information</b>  
  </summary>  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]  
</details>  
<br>  
<details>  
  <summary>  
    <b>Impedimentos</b>  
  </summary>  

</details>  
<br>

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
