### ISSUE TITLE
Documentar as rotas sob o domínio/contexto de /api/pets/breeds/ GET

### ISSUE THREAD

**Issue by Felipeness** [devhatt/pet-dex-backend#177]
**Describe the feature**
Documentar as rotas sob o domínio/contexto de /api/pets/breeds/ GET

<details open>  
  <summary>  
    <b>Description</b>  
  </summary>  
  Documentar o endpoint que retorna uma lista de raças de pets. Incluir detalhes sobre os parâmetros de consulta (se houver), formato de resposta, exemplos de uso, e status codes possíveis.  
</details>  
<br>  
<details>  
  <summary>  
    <b>Acceptance Criteria</b>  
  </summary>  
A documentação deve conter uma descrição clara da rota.<br/>  
Exemplo de requisição e resposta.<br/>  
Explicação dos status codes.<br/>  
</details>  
<br>  
<details>  
  <summary>  
    <b>Implementation Details</b>  
  </summary>  
Está no MakeFiles  
swag:  
	swag init -g api/main.go -o swagger/  
</details>  
<br>  
<details>  
  <summary>  
    <b>Visual Concepts</b>  
  </summary>  
[Include any visual representations or concepts if those are available and applicable.]  
</details>  
<br>  
<details>  
  <summary>  
    <b>Additional Information</b>  
  </summary>  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]  
</details>  
<br>  
<details>  
  <summary>  
    <b>Impedimentos</b>  
  </summary>  
Ter ferramenta de documentação implementada  
Issue: https://github.com/devhatt/pet-dex-backend/issues/119  
</details>  
<br>

**Comment by EdiltonOliveira** [comment]
Eu quero!!!
