### ISSUE TITLE
Adicionar Documentação de rota de delete de ong

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#182]
**Describe the feature**
Adicionar Documentação de rota de delete de ong
<details open>
  <summary>
    <b>Adicionar a documentação no swagger na rota `DELETE /api/ongs/{ongId}` .
    O Guia para adicionar a documentacao do Swagger está no guia de contribuicao na raiz do projeto
    </b>
  </summary>
  [Describe the new feature requested.]
</details>

<br>

<details> 
  <summary>
    <b>Use Case</b>
  </summary>
  
[Explain the use for this feature and how it might benefits the project.]
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

[Provide any details or suggestions on how this feature could be implemented.]

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by JpBurgarelli** [comment]
eu quero!!!
