### ISSUE TITLE
Documentar as rotas sob o domínio/contexto de /api/settings/push-notifications 

### ISSUE THREAD

**Issue by Felipeness** [devhatt/pet-dex-backend#185]
**Describe the feature**
Documentar as rotas sob o domínio/contexto de /api/settings/push-notifications PATCH

<details open>  
  <summary>  
    <b>Description</b>  
  </summary>  
  Documentar o endpoint que permite a atualização das configurações de notificações push. Esse endpoint é utilizado para alterar preferências relacionadas ao envio de notificações, como ativar ou desativar notificações, ajustar a frequência de envio, e definir os tipos de notificações que o usuário deseja receber. A documentação deve incluir uma descrição detalhada dos parâmetros do corpo da requisição, explicando o que cada parâmetro representa e como ele afeta o comportamento das notificações push. Além disso, deve conter o formato esperado da resposta, exemplos práticos de requisições e respostas, e uma lista completa dos status codes que podem ser retornados pelo endpoint.  
</details>  
<br>  
<details>  
  <summary>  
    <b>Acceptance Criteria</b>  
  </summary>  
A documentação deve conter a estrutura detalhada do corpo da requisição, explicando cada parâmetro.<br/>  
Exemplo de requisição e resposta, demonstrando diferentes cenários de uso (ativação, desativação, ajuste de preferências).<br/>  
Explicação clara dos status codes possíveis, com foco em erros comuns e como resolvê-los.<br/>  
</details>  
<br>  
<details>  
  <summary>  
    <b>Implementation Details</b>  
  </summary>  
Está no MakeFiles  
Issue: #119
swag:  
	swag init -g api/main.go -o swagger/  
</details>  
<br>  
<details>  
  <summary>  
    <b>Visual Concepts</b>  
  </summary>  
[Include any visual representations or concepts if those are available and applicable.]  
</details>  
<br>  
<details>  
  <summary>  
    <b>Additional Information</b>  
  </summary>  
Se o sistema utiliza algum middleware específico para validação das configurações de notificações push, isso deve ser mencionado aqui. Além disso, se houver alguma limitação, como o número máximo de notificações que podem ser configuradas ou restrições específicas de dispositivos, essas informações devem ser incluídas.  
</details>  
<br>  
<details>  
  <summary>  
    <b>Impedimentos</b>  
  </summary>  

</details>  
<br>

**Comment by PiluVitu** [comment]
Eu quero!!!
