### ISSUE TITLE
Fazer docker file

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#25]
**Descreva a funcionalidade**
Criar um arquivo Dockerfile para construir uma imagem Docker da aplicação.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Definir um arquivo Dockerfile que instrui o Docker sobre como construir a imagem da aplicação, incluindo as dependências e configurações necessárias.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é útil para encapsular a aplicação e suas dependências em uma imagem Docker, permitindo que ela seja distribuída e executada de forma consistente em diferentes ambientes.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Criar um arquivo chamado `Dockerfile` na raiz do projeto.
- Utilizar uma imagem base adequada ao ambiente de execução da aplicação.
- Incluir instruções para copiar o código fonte da aplicação para o container.
- Instalar dependências, configurar variáveis de ambiente e realizar outras configurações necessárias.
- Especificar o comando de inicialização da aplicação.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois envolve principalmente configurações em um arquivo de texto.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Certifique-se de documentar claramente as dependências e configurações no Dockerfile. Isso facilitará a manutenção e a compreensão do processo de construção da imagem Docker. Testar a imagem em diferentes ambientes antes de distribuí-la é recomendado.
</details>

**Comment by Lefel95** [comment]
5

**Comment by lucasvsouza28** [comment]
EU QUERO !!!

**Comment by lucasvsouza28** [comment]
EU QUERO!!!

**Comment by GabrielGSD** [comment]
@lucasvsouza28 você chegou a fazer? Pois eu estava pensando em pegar essa, #26 e a #27. Mas qualquer coisa podemos ver juntos essas tasks, o que você acha?

**Comment by lucasvsouza28** [comment]
> @lucasvsouza28 você chegou a fazer? Pois eu estava pensando em pegar essa, #26 e a #27. Mas qualquer coisa podemos ver juntos essas tasks, o que você acha?

Acabei de fazer com multi-stage inclusive, vou mandar o PR já já
