### ISSUE TITLE
Implementar um build multistage no Dockerfile

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#26]
**Descreva a funcionalidade**
Implementar um build multistage no Dockerfile para otimizar a construção da imagem Docker, separando as fases de construção e produção.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Utilizar um build multistage no Dockerfile para dividir o processo de construção da imagem Docker em estágios, permitindo a criação de uma imagem mais leve e eficiente para produção.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é útil para reduzir o tamanho final da imagem Docker, removendo dependências de construção que não são necessárias para a execução da aplicação em produção.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Dividir o Dockerfile em estágios, identificando as dependências de construção e os artefatos necessários para a execução da aplicação.
- Utilizar diferentes imagens base para cada estágio, como uma imagem com todas as dependências de construção e outra apenas com as dependências necessárias em produção.
- Copiar apenas os artefatos essenciais do estágio de construção para o estágio de produção.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois envolve principalmente configurações em um arquivo de texto.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Certifique-se de testar a imagem gerada em diferentes ambientes para garantir que todas as dependências necessárias estejam presentes no estágio de produção. Documentar claramente as etapas e as decisões tomadas durante o processo é recomendado.
</details>

**Comment by Lefel95** [comment]
13
