### ISSUE TITLE
Fazer Docker compose

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#27]
**Descreva a funcionalidade**
Criar um arquivo Docker Compose para facilitar a execução e a gestão de containers necessários para o projeto.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Definir um arquivo Docker Compose que especifica como os serviços (aplicação, banco de dados, cache, etc.) devem ser configurados e executados em containers.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é útil para padronizar e simplificar o processo de execução do projeto em diferentes ambientes. O Docker Compose permite que todos os serviços necessários sejam configurados e iniciados com um único comando.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Criar um arquivo `docker-compose.yml` na raiz do projeto.
- Definir serviços para a aplicação, banco de dados, cache e outros componentes necessários.
- Configurar as redes, volumes e outras configurações necessárias para a comunicação entre os containers.
- Utilizar variáveis de ambiente no arquivo Docker Compose para parametrizar configurações.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois envolve principalmente configurações em um arquivo de texto.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Documentar as configurações no arquivo Docker Compose e garantir que as variáveis de ambiente sejam configuradas de acordo com os requisitos do projeto. Isso facilitará a colaboração e a reprodução do ambiente em diferentes máquinas.
</details>

**Comment by Lefel95** [comment]
8

**Comment by felipelaraujo** [comment]
EU QUERO!!!
