### ISSUE TITLE
Fazer Setup do EC2 e de outros sistemas (Mysql, Reddis)

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#28]
**Descreva a funcionalidade**
Realizar o setup das Lambdas em GO na AWS e de outros sistemas como MySQL e Redis para suportar a infraestrutura do projeto.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Configurar e provisionar instâncias do EC2 para hospedar a aplicação, bem como configurar instâncias do MySQL e Redis para armazenamento de dados e cache, respectivamente.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é essencial ao iniciar um projeto que requer infraestrutura em nuvem. Configurar instâncias do EC2 permite hospedar a aplicação, enquanto o MySQL e o Redis fornecem serviços de banco de dados e cache, respectivamente.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Criar uma instância do EC2 na AWS e instalar as dependências necessárias, incluindo a configuração do ambiente de execução da aplicação.
- Provisionar instâncias do MySQL e Redis, configurando as credenciais e as configurações adequadas.
- Configurar as regras de firewall (grupos de segurança) para permitir o tráfego necessário nas instâncias do EC2 e nos bancos de dados.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois envolve principalmente configurações em consoles de nuvem e terminais.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Certifique-se de seguir as práticas recomendadas de segurança ao configurar instâncias do EC2 e os bancos de dados. Documentar as configurações e credenciais usadas é crucial para a manutenção futura da infraestrutura.
</details>

**Comment by Lefel95** [comment]
21
