### ISSUE TITLE
Fazer setup de github actions

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#29]
**Descreva a funcionalidade**
Configurar o GitHub Actions para automação de tarefas no repositório do GitHub.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Implementar um conjunto de workflows no GitHub Actions para automatizar tarefas como testes, build, deploy, ou qualquer outra ação desejada no repositório do GitHub.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é útil para automatizar processos repetitivos, como execução de testes automatizados, criação de builds, ou implantação contínua, melhorando a eficiência do desenvolvimento e garantindo a consistência nas operações do repositório.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Criar um arquivo de configuração para o GitHub Actions no repositório.
- Definir workflows que incluem os passos necessários para realizar as tarefas desejadas, como execução de testes, construção de artefatos, ou implantação em ambientes de produção.
- Configurar gatilhos para acionar os workflows em eventos específicos, como push, pull request, ou cron jobs.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois envolve principalmente configurações de scripts e pipelines de automação.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Certifique-se de documentar os workflows criados e fornecer instruções claras sobre como outros colaboradores podem contribuir para e se beneficiar dessas automações. Além disso, teste os workflows em diferentes cenários para garantir a confiabilidade das automações.

**Comment by Lefel95** [comment]
13

**Comment by PiluVitu** [comment]
- Qual o provedor que iremos fazer deploy ? 
    - Dependendo da provedora já conseguiremos deployar automaticamente
