### ISSUE TITLE
Desenvolver endpoint de atualizar usuário

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#31]
**Descreva a funcionalidade**
Desenvolver um endpoint para atualizar informações do usuário, permitindo a modificação das propriedades Nome, Sobrenome, Celular, Data de Nascimento, Local, Imagem de Perfil (URL) e E-mail.
Esse endpoint tem que ser coberto por uma camada de autenticacao, para permitir que somente usuarios logados, façam atualizações no perfil deles mesmos.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Criar um endpoint que aceite solicitações para atualização de informações do usuário, permitindo a modificação de propriedades específicas como Nome, Sobrenome, Celular, Data de Nascimento, Local, Imagem de Perfil (URL) e E-mail.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Esta funcionalidade é útil quando os usuários desejam atualizar ou corrigir informações pessoais em sua conta, como detalhes de contato, data de nascimento ou localização.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Implementar um endpoint HTTP (por exemplo, PATCH ou PUT) para receber solicitações de atualização de informações do usuário.
- Validar se o usuario autenticado é o mesmo usuario que está atualizando
- Validar as informações recebidas, garantindo que estejam de acordo com as regras de negócios e requisitos do sistema.
- Atualizar as propriedades do usuário no banco de dados com base nas informações fornecidas.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-backend/assets/13355406/5f253827-b696-4926-8399-b042ab0306ae)
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
É importante documentar claramente quais propriedades do usuário podem ser atualizadas, as validações aplicadas e os possíveis retornos do endpoint. Certifique-se de garantir a segurança da operação, incluindo autenticação adequada e controle de acesso.
</details>

**Comment by wellington-tinho** [comment]
EU QUERO!!!

**Comment by wellington-tinho** [comment]
!leave

**Comment by Lefel95** [comment]
13

**Comment by Sherlockzen** [comment]
Eu quero!!!

**Comment by kvnbg** [comment]
EU QUERO!!!
