### ISSUE TITLE
Fazer fluxo de reset de senha

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#32]
**Descreva a funcionalidade**
Implementar um fluxo de redefinição de senha que exige a inserção da senha antiga, a nova senha (com confirmação) e realiza verificações de segurança, incluindo a atualização da senha com criptografia.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Criar um processo de redefinição de senha mais seguro, onde os usuários devem fornecer um email, a nova senha e confirmar a nova senha. Durante o processo, realizar verificações de segurança e garantir que a nova senha seja armazenada de forma criptografada no banco de dados.
</details>

<br>

<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>
  
[Task ](https://github.com/devhatt/pet-dex-backend/issues/37)
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Esta funcionalidade é aplicável quando os usuários desejam alterar suas senhas por motivos de segurança. Exigir uma confirmação por OTP e confirmar a nova senha ajuda a garantir a autenticidade do usuário e a prevenir alterações não autorizadas.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Implementar um endpoint para solicitação de redefinição de senha, exigindo o email, e enviar um OTP via email.
- Implementar o envio de email, com a biblioteca ja existente no projeto
- Verificar a autenticidade do usuário por meio da OTP antes de permitir a redefinição.
- Utilizar algoritmos de criptografia adequados para armazenar a nova senha no banco de dados.
- Verificar se as duas senhas Nova e Confirmação são iguais
- Implementar uma lógica para verificar a complexidade da senha, como requisitos de comprimento mínimo, caracteres especiais, etc.
</details>

<br>

<details> 
  <summary>
    <b>Impedimentos</b>
  </summary>
     - Ter todo o fluxo de autenticação feito
     - Ter todo o fluxo de login feito
     
     Esta sendo resolvido no PR abaixo:
      - https://github.com/devhatt/pet-dex-backend/pull/88
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-backend/assets/13355406/f38e8312-ed8b-4c78-bcfc-0f7dfade441c)
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Garantir que a nova senha seja tratada com segurança, utilizando boas práticas de criptografia. Além disso, fornecer feedback claro aos usuários durante o processo para garantir uma experiência de usuário eficiente.
</details>

**Comment by Caixetadev** [comment]
Eu quero

**Comment by k1nha** [comment]
> Eu quero

Comenta usando ````eu quero!!!``

**Comment by Caixetadev** [comment]
eu quer!!!

**Comment by Caixetadev** [comment]
eu quero!!!

**Comment by Lefel95** [comment]
21

**Comment by davidspader** [comment]
Eu quero!!!

**Comment by patrickn2** [comment]
Eu quero!!!
