### ISSUE TITLE
Adicionar autenticação aos fluxos de configuração de usuários.

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#33]
**Descreva a funcionalidade**
Adicionar autenticação aos fluxos de configuração de usuários.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Implementar um mecanismo de autenticação para os fluxos de configuração de usuários, garantindo que apenas usuários autenticados possam realizar ações de configuração.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Essa funcionalidade é essencial para proteger os fluxos de configuração de usuários contra acesso não autorizado. Ela beneficia o projeto ao garantir que apenas usuários autenticados possam realizar ações como atualizar preferências, alterar configurações de segurança ou acessar informações sensíveis do perfil.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Implementar um sistema de autenticação que valide as credenciais do usuário antes de permitir o acesso aos fluxos de configuração.
- Utilizar tokens de autenticação seguros para verificar a identidade do usuário.
- Integrar a autenticação nos endpoints específicos que lidam com os fluxos de configuração de usuários.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois está relacionada a uma implementação nos bastidores sem uma interface visual explícita.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Garantir que a autenticação seja realizada de forma segura, utilizando práticas recomendadas de segurança, como hashing de senhas e gestão adequada de tokens de autenticação. Além disso, documentar os processos de autenticação facilitará a compreensão e manutenção futura do código.
</details>

**Comment by Lefel95** [comment]
13
