### ISSUE TITLE
Fazer integração com sistema de email

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#35]
**Descreva a funcionalidade**
Integrar o sistema de e-mail para enviar notificações, utilizando um pacote de e-mail e um repositório já criados para essa finalidade.

<details open>
  <summary>
    <b>Descrição</b>
  </summary>
  Implementar uma funcionalidade que permite o envio de notificações por e-mail aos usuários, utilizando um pacote de e-mail e um repositório específico já existentes. O pacote de e-mail encapsula a lógica de envio de e-mails, enquanto o repositório lida com a persistência e recuperação de dados relacionados às notificações por e-mail.
</details>

<br>

<details> 
  <summary>
    <b>Cenário de Uso</b>
  </summary>
  
Esta funcionalidade é útil para enviar notificações importantes aos usuários por meio de e-mails. Pode ser usado em cenários como confirmações de cadastro, recuperação de senha ou qualquer outro evento que exija comunicação imediata com o usuário por e-mail. Isso melhora a experiência do usuário e mantém os usuários informados sobre eventos relevantes.
</details>

<br>

<details> 
  <summary>
    <b>Detalhes de Implementação</b>
  </summary>

- Utilizar o pacote de e-mail existente, que possui uma implementação concreta do serviço de e-mail.
- Criar um repositório específico para notificações por e-mail, utilizando a interface `EmailNotificationRepository` que contém métodos para enviar diferentes tipos de notificações.
- Integrar o repositório de notificações por e-mail nos pontos do código onde as notificações são necessárias, como confirmação de cadastro, atualização de preferências, etc.
</details>

<br>

<details> 
  <summary>
    <b>Conceitos Visuais</b>
  </summary>

[Não aplicável para esta funcionalidade, pois é uma implementação nos bastidores sem uma interface visual explícita.]
</details>

<br>

<details> 
  <summary>
    <b>Informações Adicionais</b>
  </summary>
  
Certifique-se de configurar corretamente as credenciais do servidor SMTP no pacote de e-mail para garantir o correto funcionamento do envio de notificações por e-mail. Além disso, documente a nova funcionalidade para facilitar a manutenção e compreensão futuras do código.
</details>

**Comment by k1nha** [comment]
Essa issue não se enquadraria junto a essa #37?
O setup do email provider já implementaria o repository

**Comment by k1nha** [comment]
eu quero!!!

**Comment by Lefel95** [comment]
21

**Comment by k1nha** [comment]
a ideia dessa integração é ter um package dentro da aplicação?
