### ISSUE TITLE
Fazer Layer de repositório e package de email

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#37]
**Descreva a funcionalidade**
Implementação de uma camada de repositório para o envio de e-mails, utilizando um pacote de e-mail como componente independente para gerenciar a lógica de envio de mensagens eletrônicas.

**Descrição**
Esta camada de repositório é responsável por utilizar um pacote de e-mail para enviar mensagens eletrônicas em diferentes contextos do sistema, como confirmações de cadastro, notificações e recuperação de senha. O pacote de e-mail encapsula a complexidade do envio de e-mails e permite a substituição fácil do provedor de e-mails.

**Cenário de Uso**
A camada de repositório é empregada por diferentes partes do sistema para enviar e-mails em diferentes situações. O pacote de e-mail é um componente modular que pode ser reutilizado em diversas partes do sistema sem a necessidade de duplicação de código.

**Detalhes de Implementação**

1. **Camada de Repositório:**
   - Crie uma interface para o repositório de envio de e-mails, contendo métodos para enviar diferentes tipos de e-mails.
   - Implemente a lógica para utilizar o pacote de e-mail no envio de mensagens.

   ```go
   // Exemplo de interface para o repositório de envio de e-mails
   type EmailRepository interface {
     SendConfirmationEmail(user User) error
     SendNotificationEmail(message string, recipient Email) error
     // ... outros métodos relacionados a e-mails
   }

   // Implementação do repositório que utiliza um pacote de e-mail
   type EmailRepositoryImpl struct {
     EmailService EmailService
   }

   func (repo *EmailRepositoryImpl) SendConfirmationEmail(user User) error {
     // Lógica específica para enviar e-mail de confirmação usando o EmailService
     return repo.EmailService.SendConfirmationEmail(user)
   }

   func (repo *EmailRepositoryImpl) SendNotificationEmail(message string, recipient Email) error {
     // Lógica específica para enviar e-mail de notificação usando o EmailService
     return repo.EmailService.SendNotificationEmail(message, recipient)
   }
   ```

2. **Pacote de E-mail:**
   - Desenvolva um pacote de e-mail independente que encapsula a lógica de envio de e-mails.
   - Forneça uma interface para facilitar a substituição de provedores de e-mail.

   ```go
   // Exemplo de interface para o pacote de e-mail
   type EmailService interface {
     SendConfirmationEmail(user User) error
     SendNotificationEmail(message string, recipient Email) error
     // ... outros métodos relacionados a e-mails
   }

   // Implementação do pacote de e-mail usando um provedor específico
   type SMTPEmailService struct {
     // Configurações específicas do provedor SMTP
   }

   func (service *SMTPEmailService) SendConfirmationEmail(user User) error {
     // Lógica para enviar e-mail de confirmação usando SMTP
   }

   func (service *SMTPEmailService) SendNotificationEmail(message string, recipient Email) error {
     // Lógica para enviar e-mail de notificação usando SMTP
   }
   ```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
Documente a camada de repositório e o pacote de e-mail para garantir uma compreensão clara de como essas funcionalidades são projetadas e utilizadas em diferentes partes do sistema. Certifique-se de implementar tratamentos adequados de erros e logging para monitorar e depurar possíveis problemas.

**Comment by Lefel95** [comment]
21

**Comment by GabrielTrindadeC** [comment]
eu quero!!!

**Comment by davidspader** [comment]
EU QUERO!!!

**Comment by muritadb** [comment]
eu quero!!!
