### ISSUE TITLE
Endpoint para Mostrar Dados do pet para adocao

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#38]
**Descreva a funcionalidade**
Implementação de um endpoint para mostrar os dados de um animal disponível para adoção, incluindo imagem, localização, informações do pet e links para redes sociais da ONG responsável.

**Descrição**
Essa funcionalidade visa fornecer informações completas sobre um animal disponível para adoção, incluindo uma imagem representativa, a localização da ONG, detalhes específicos sobre o pet e links para as redes sociais da organização responsável.

**Cenário de Uso**
A exibição de dados de um pet para adoção é útil quando potenciais adotantes desejam obter informações detalhadas sobre um animal específico antes de tomar a decisão de adoção.

**Detalhes de Implementação**
A implementação envolve a criação de um novo endpoint que recebe o identificador único do pet para adoção como parâmetro. O sistema deve então recuperar as informações do pet e da ONG associada e retornar uma resposta contendo todos os dados relevantes.

**Exemplo de Requisição**
```json
GET /api/pets-para-adocao/{id}
```

**Exemplo de Resposta**
```json
{
  "id": 1,
  "nome": "Bella",
  "imagem": "https://example.com/bella.jpg",
  "localizacao_ong": {
    "endereco": "Rua Exemplo, 123",
    "cidade": "Cidade",
    "estado": "Estado"
  },
  "dados_pet": {
    "raca": "Vira-lata",
    "idade": 2,
    "porte": "Médio",
    // ... outras propriedades
  },
  "redes_sociais_ong": {
    "facebook": "https://www.facebook.com/ong.example",
    "instagram": "https://www.instagram.com/ong_example"
  }
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint de exibição de dados do pet para adoção deve ser elaborada e disponibilizada aos desenvolvedores e usuários finais. Certifique-se de que apenas pets disponíveis para adoção sejam acessíveis por meio deste endpoint.

**Comment by Lefel95** [comment]
13
