### ISSUE TITLE
Listar pets do usuário

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#39]
**Descreva a funcionalidade**
Implementação de um endpoint para listar os animais (Pets) associados a um usuário autenticado no sistema.

**Descrição**
Essa funcionalidade permite que usuários autenticados obtenham uma lista dos seus animais de estimação registrados no sistema, facilitando o gerenciamento e a visualização dos animais associados à sua conta.

**Cenário de Uso**
A listagem de pets do usuário é útil quando os proprietários desejam revisar ou gerenciar informações específicas sobre os animais que possuem registrados no sistema.

**Detalhes de Implementação**
A implementação envolve a criação de um novo endpoint que requer autenticação. Este endpoint deve recuperar os dados dos animais associados ao usuário autenticado no sistema e retornar uma resposta contendo a lista de animais.

**Exemplo de Requisição**
```json
GET /api/meus-pets
```

**Exemplo de Resposta**
```json
[
  {
    "id": 1,
    "nome": "Max",
    "raca": "Labrador Retriever",
    "idade": 3,
    // ... outras propriedades
  },
  {
    "id": 2,
    "nome": "Luna",
    "raca": "Siamês",
    "idade": 2,
    // ... outras propriedades
  }
]
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint de listagem de pets do usuário deve ser elaborada e disponibilizada aos desenvolvedores e usuários finais. Certifique-se de que apenas usuários autenticados tenham acesso a este endpoint.

**Comment by davidspader** [comment]
EU QUERO!!!
