### ISSUE TITLE
Cadastro de ONG

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#40]
**Descreva a funcionalidade**
Implementação de um endpoint para cadastrar uma ONG no sistema, permitindo a inclusão das seguintes propriedades: CNPJ, e-mail, localização (objeto contendo endereço, cidade, estado), imagem e redes sociais.

**Descrição**
Esta funcionalidade possibilita o registro de organizações não governamentais (ONGs) no sistema, fornecendo informações essenciais, como CNPJ, endereço de e-mail, localização (objeto contendo endereço, cidade, estado), imagem representativa da ONG e links para suas redes sociais.

**Cenário de Uso**
O cadastro de ONGs é útil para organizações que desejam se registrar no sistema para divulgar suas atividades, receber apoio e facilitar a adoção de animais.

**Detalhes de Implementação**
A implementação envolve a criação de um novo endpoint para o cadastro de ONGs. Este endpoint deve aceitar uma requisição contendo as informações necessárias, como CNPJ, e-mail, localização (objeto), imagem e redes sociais, e inserir os dados da ONG no banco de dados.

**Exemplo de Requisição**
```json
POST /api/ongs
{
  "cnpj": "12345678901234",
  "email": "ong@example.com",
  "localizacao": {
    "endereco": "Rua Exemplo, 123",
    "cidade": "Cidade",
    "estado": "Estado"
  },
  "imagem": "https://example.com/ong.jpg",
  "redes_sociais": {
    "facebook": "https://www.facebook.com/ong.example",
    "instagram": "https://www.instagram.com/ong_example"
  }
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint de cadastro de ONGs deve ser elaborada e disponibilizada aos desenvolvedores e usuários finais. Certifique-se de que as imagens fornecidas sejam acessíveis e relevantes para representar visualmente cada ONG. Além disso, valide a autenticidade do CNPJ e a formatação correta do e-mail durante o processo de cadastro.

**Comment by Lefel95** [comment]
13

**Comment by luanc202** [comment]
Eu quero!

**Comment by luanc202** [comment]
Eu quero!!!

**Comment by Clerijr** [comment]
Eu quero!!!
