### ISSUE TITLE
Trazer listagem de Raças com links de fotos e nomes

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#41]
**Descreva a funcionalidade**
Implementação de um endpoint para listar as raças de animais (Pet), fornecendo informações como nome da raça, link para foto representativa e identificador único (ID).

**Descrição**
Essa funcionalidade tem como objetivo oferecer aos usuários uma lista de raças de animais disponíveis no sistema, apresentando detalhes como o nome da raça, um link para uma foto representativa e o identificador único associado à raça.

**Cenário de Uso**
A listagem de raças é útil para os usuários que desejam explorar as diferentes raças de animais disponíveis no sistema, proporcionando uma visão geral e informativa sobre as características de cada raça.

**Detalhes de Implementação**
A implementação envolve a criação de um novo endpoint para listar as raças de animais. Esse endpoint deve recuperar as informações necessárias do banco de dados e retornar uma resposta que inclua o nome da raça, um link para uma foto representativa e o identificador único (ID) associado à raça.

**Exemplo de Resposta**
```json
GET /api/racas
[
  {
    "id": 1,
    "nome": "Labrador Retriever",
    "foto": "https://example.com/labrador.jpg"
  },
  {
    "id": 2,
    "nome": "Bulldog Francês",
    "foto": "https://example.com/bulldog.jpg"
  },
  // ... outras raças
]
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint de listagem de raças deve ser elaborada e disponibilizada aos desenvolvedores e usuários finais. Certifique-se de que as imagens fornecidas nos links sejam acessíveis e relevantes para representar visualmente cada raça.

**Comment by wellington-tinho** [comment]
Eu quero!!!

**Comment by Lefel95** [comment]
8

**Comment by ropehapi** [comment]
Eu quero!!!

**Comment by JonySamarelli** [comment]
Eu quero!!!
