### ISSUE TITLE
Fazer Endpoint de Cadastro de pet (Nome e RacaID e UserID)

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#42]
**Descreva a funcionalidade**
Implementação de um endpoint para cadastrar um novo animal (Pet) no sistema, permitindo a inclusão das propriedades "Nome", "RacaID" e "UserID" associado ao proprietário do animal.

**Descrição**
Essa funcionalidade tem como objetivo possibilitar o cadastro de novos animais no sistema, permitindo que os usuários informem o nome do pet, sua raça e associem o animal ao seu respectivo usuário por meio do "UserID".

**Cenário de Uso**
O cadastro de pets é útil quando os usuários desejam incluir informações sobre seus animais de estimação no sistema, mantendo um registro organizado e associando cada animal ao seu proprietário.

**Detalhes de Implementação**
A implementação envolve a criação de um novo endpoint para cadastro de pets. Esse endpoint deve aceitar uma requisição contendo as informações necessárias, como "Nome", "Raça" e "UserID", e inserir os dados do animal no banco de dados, associando-o ao usuário correspondente.

**Exemplo de Requisição**
```json
POST /api/pets
{
  "nome": "Max",
  "racaID": 1,
  "userID": 123456
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint de cadastro de pets deve ser elaborada e disponibilizada aos desenvolvedores e usuários finais. Testes extensivos devem ser conduzidos para garantir a correta funcionalidade do endpoint e a integração adequada dos dados no banco de dados.

**Comment by gustavomaisatto** [comment]
Eu quero!!!

**Comment by Lefel95** [comment]
13

**Comment by luanc202** [comment]
Eu quero!

**Comment by luanc202** [comment]
Eu quero!!!
