### ISSUE TITLE
Fazer Endpoint de Atualizar Pet

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#43]
**Descreva a funcionalidade**
Implementação de um endpoint para atualizar informações de um animal (Pet), permitindo que a propriedade "Porte" seja recebida e atualizada.

**Descrição**
Essa funcionalidade tem como objetivo ampliar a flexibilidade do sistema ao permitir que a propriedade "Porte" de um animal seja atualizada através de um endpoint específico. Isso possibilitará a gestão mais completa das informações sobre o animal, incluindo detalhes sobre o seu tamanho.

**Cenário de Uso**
A adição da capacidade de atualizar a propriedade "Porte" é útil quando os usuários necessitam modificar informações específicas sobre um animal, como seu tamanho, após o registro inicial.

**Detalhes de Implementação**
A implementação envolverá a criação de um endpoint dedicado para atualização de pets, permitindo que os clientes enviem uma requisição com as informações do pet, incluindo o novo valor para a propriedade "Porte". A lógica no backend deverá validar e processar a requisição, atualizando o porte do animal no banco de dados.

**Exemplo de Requisição**
```json
PATCH /api/pets/{id}
{
  "porte": "Médio"
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint deve ser atualizada para refletir essa nova capacidade, e os desenvolvedores e usuários finais devem ser informados sobre a existência e uso desse recurso. Testes abrangentes devem ser realizados para garantir o correto funcionamento do endpoint de atualização do pet com a inclusão da propriedade "Porte".

**Comment by iasarchi** [comment]
EU QUERO!!!
