### ISSUE TITLE
Escolher biblioteca de criptografia

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#44]
**Descreva a funcionalidade**
Conduzir um estudo para selecionar e implementar uma biblioteca de criptografia apropriada para armazenar e gerenciar as senhas dos usuários no sistema.

**Descrição**
Esta funcionalidade visa melhorar a segurança do sistema por meio da escolha cuidadosa e implementação de uma biblioteca de criptografia para proteger as senhas dos usuários armazenadas. A biblioteca selecionada deve oferecer algoritmos robustos e práticas seguras para garantir a integridade das informações confidenciais.

**Cenário de Uso**
A implementação de uma biblioteca de criptografia para senhas reforça a proteção contra ameaças de segurança, garantindo que as informações sensíveis dos usuários permaneçam confidenciais mesmo em caso de comprometimento do banco de dados.

**Detalhes de Implementação**
O estudo deve abranger a pesquisa de bibliotecas de criptografia amplamente reconhecidas e utilizadas na comunidade de desenvolvimento. Após a seleção, a integração da biblioteca no sistema requer a adaptação da lógica de armazenamento e validação de senhas para utilizar os métodos fornecidos pela biblioteca.

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação resultante do estudo deve abordar os critérios utilizados para a escolha da biblioteca de criptografia, bem como fornecer instruções claras para a implementação e configuração no sistema. A equipe de desenvolvimento deve ser treinada sobre as melhores práticas para o uso da biblioteca selecionada, e os testes devem ser conduzidos para garantir a eficácia e segurança da solução.

**Comment by Lefel95** [comment]
13
