### ISSUE TITLE
Fazer Sistema de SSO

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#46]
Descreva a funcionalidade
Implementação do login por Single Sign-On (SSO), permitindo que os usuários acessem o sistema de forma autenticada através de uma única credencial, geralmente fornecida por um provedor de identidade externo.

Descrição
Esta funcionalidade propõe a adoção do Single Sign-On como método de autenticação, eliminando a necessidade de credenciais específicas do sistema. Os usuários serão redirecionados para um provedor de identidade externo, onde realizarão o login uma vez. Após a autenticação bem-sucedida, serão automaticamente autenticados em todos os sistemas conectados via SSO.

Cenário de Uso
O login por SSO oferece uma experiência simplificada aos usuários, evitando a necessidade de lembrar e gerenciar várias credenciais. Isso é especialmente útil em ambientes corporativos com diversos sistemas, nos quais os usuários podem acessar aplicativos e serviços diferentes com uma única autenticação.

Detalhes de Implementação
A implementação do login por SSO envolve a integração com um provedor de identidade externo, configurando a comunicação segura entre o sistema e o provedor. Será necessário estabelecer a lógica de redirecionamento para o provedor de identidade, a manipulação dos tokens de autenticação retornados e a criação/atualização da sessão do usuário no sistema.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
A documentação deve incluir instruções claras sobre como os usuários podem utilizar o login por SSO, além de orientações para a administração do sistema em relação à configuração e manutenção dessa integração. A comunicação com os usuários e a equipe de suporte é fundamental para garantir uma transição suave para essa nova forma de autenticação.

**Comment by Lefel95** [comment]
21

**Comment by patrickn2** [comment]
Eu quero!!!
