### ISSUE TITLE
Estudar como funcionaria uma hierarquia de roles 

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#48]
Descreva a funcionalidade
Conduzir um estudo sobre a implementação de uma hierarquia de funções (roles) de usuários utilizando um repositório de dados, com o objetivo de compreender o funcionamento e os benefícios dessa estruturação para gerenciamento de permissões.

Descrição
Esta funcionalidade propõe uma análise detalhada sobre a criação e administração de uma hierarquia de funções de usuários por meio de um repositório de dados. O intuito é compreender como essa hierarquia pode ser modelada e armazenada eficientemente, facilitando a gestão de permissões e garantindo uma abordagem flexível e escalável.

Cenário de Uso
A implementação de uma hierarquia de funções de usuários é crucial para sistemas nos quais diferentes níveis de autoridade precisam ser estabelecidos. Essa abordagem proporciona uma maneira estruturada de atribuir e gerenciar permissões, adequando-se a ambientes complexos e organizações com diversos níveis hierárquicos.

Detalhes de Implementação
O estudo abordará a modelagem da hierarquia de funções de usuários, levando em consideração aspectos como a relação entre roles, a herança de permissões e a flexibilidade na atribuição de funções a usuários específicos. Será necessário também explorar como essas informações podem ser eficientemente armazenadas e consultadas em um repositório de dados.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
A documentação resultante do estudo deve destacar as melhores práticas na criação de hierarquias de funções de usuários, apresentando possíveis modelos de dados e estratégias para armazenamento em repositórios de dados específicos. As conclusões do estudo devem ser compartilhadas com a equipe de desenvolvimento para orientar futuras implementações relacionadas à gestão de permissões de usuários.

**Comment by Lefel95** [comment]
21

**Comment by Felipeness** [comment]
Manda pra ca

**Comment by Felipeness** [comment]
Introdução:

A hierarquia de funções (roles) de usuários, quando bem implementada, oferece uma solução robusta e escalável para esses desafios. Este texto explora a implementação de uma hierarquia de funções de usuários, utilizando um repositório de dados, com o objetivo de analisar seu funcionamento e benefícios no gerenciamento de permissões em sistemas complexos. Além de ajudar na compreensão do tema, o estudo busca apresentar modelos práticos e estratégias eficazes para a implementação dessas hierarquias em ambientes organizacionais.

Modelagem da Hierarquia de Funções:

1. Princípios da Modelagem de Hierarquia de Funções
Definição de Funções e Subfunções: Exploração das práticas para definir funções (roles) e como elas podem ser subdivididas para refletir a estrutura organizacional de uma empresa ou sistema.
Relacionamento entre Funções: Análise de como diferentes roles se relacionam entre si, incluindo conceitos de herança de permissões e sobreposição de funções.
2. Herança de Permissões
Mecanismos de Herança: Discussão sobre como as permissões podem ser herdadas dentro da hierarquia, permitindo eficiência e consistência na gestão de acessos.
Controle e Flexibilidade: Avaliação de como manter um equilíbrio entre controle centralizado e flexibilidade para adaptações locais nas atribuições de permissões.
3. Estratégias de Modelagem
Modelos de Dados para Hierarquias de Funções: Comparação entre diferentes abordagens de modelagem, como estruturas em árvore, modelos relacionais e não relacionais.
Escalabilidade e Manutenção: Discussão sobre a importância de considerar a escalabilidade e a facilidade de manutenção ao modelar a hierarquia de funções.
Armazenamento e Consulta em Repositórios de Dados

1. Escolha do Repositório de Dados
Tipos de Repositórios: Análise das características de diferentes tipos de repositórios de dados, como SQL (relacional) e NoSQL (não-relacional), e como eles se adequam ao armazenamento de informações de roles.
Critérios de Seleção: Discussão sobre os critérios para escolher um repositório de dados, considerando fatores como o tamanho da organização, a complexidade da hierarquia de funções e requisitos específicos de desempenho.
2. Implementação do Armazenamento de Dados
Modelagem de Dados para Armazenamento: Exploração de como estruturar os dados dentro do repositório escolhido, mantendo a integridade e a eficiência de acesso.
Segurança e Proteção de Dados: Discussão sobre as medidas de segurança necessárias para proteger as informações de roles e permissões armazenadas.
3. Consulta e Gerenciamento de Dados
Mecanismos de Consulta: Análise de como recuperar e gerenciar informações sobre roles e permissões de maneira eficiente.
Desempenho e Otimização: Considerações sobre o desempenho das consultas e estratégias para otimizar o acesso aos dados em diferentes cenários de uso.

Armazenamento e Consulta em Repositórios de Dados:

1. Escolha do Repositório de Dados
Tipos de Repositórios: Análise das características de diferentes tipos de repositórios de dados, como SQL (relacional) e NoSQL (não-relacional), e como eles se adequam ao armazenamento de informações de roles.
Critérios de Seleção: Discussão sobre os critérios para escolher um repositório de dados, considerando fatores como o tamanho da organização, a complexidade da hierarquia de funções e requisitos específicos de desempenho.
2. Implementação do Armazenamento de Dados
Modelagem de Dados para Armazenamento: Exploração de como estruturar os dados dentro do repositório escolhido, mantendo a integridade e a eficiência de acesso.
Segurança e Proteção de Dados: Discussão sobre as medidas de segurança necessárias para proteger as informações de roles e permissões armazenadas.
3. Consulta e Gerenciamento de Dados
Mecanismos de Consulta: Análise de como recuperar e gerenciar informações sobre roles e permissões de maneira eficiente.
Desempenho e Otimização: Considerações sobre o desempenho das consultas e estratégias para otimizar o acesso aos dados em diferentes cenários de uso.

Melhores Práticas e Recomendações:

1. Modelagem de Hierarquia de Funções
Clareza e Consistência: Enfatizar a importância de uma modelagem clara e consistente das funções para evitar confusões e brechas de segurança.
Flexibilidade e Escalabilidade: Recomendações para garantir que a hierarquia de funções seja flexível e escalável, adaptando-se às mudanças organizacionais e ao crescimento.
2. Escolha de Repositórios de Dados
Adequação ao Contexto: Orientações sobre como escolher um repositório de dados que se alinhe com as necessidades específicas do sistema e da organização.
Segurança de Dados: Ressaltar a importância de implementar medidas robustas de segurança de dados, especialmente em sistemas que gerenciam informações sensíveis.
3. Gestão e Manutenção
Monitoramento e Atualização: Discutir a importância do monitoramento contínuo e da atualização regular do sistema de gestão de permissões para lidar com novas ameaças e mudanças organizacionais.
Treinamento e Conscientização: Sublinhar a necessidade de treinar adequadamente os usuários e administradores do sistema para garantir o uso correto e seguro das permissões.
4. Adoção de Padrões e Regulamentações
Conformidade com Padrões: Encorajar a adoção de padrões de indústria e regulamentações relevantes para garantir a integridade e a legalidade do sistema de gestão de permissões.

O modelo de hierarquia de funções (roles) mais utilizado atualmente em sistemas de informação é o Role-Based Access Control (RBAC). O RBAC se tornou um padrão de facto para gerenciamento de permissões e controle de acesso devido à sua flexibilidade, eficiência e capacidade de se adaptar a diversas necessidades organizacionais.

Características do RBAC:
 
Definição de Funções (Roles): No RBAC, as permissões não são atribuídas diretamente aos usuários individuais, mas sim a funções. Essas funções representam um conjunto de permissões que refletem as responsabilidades e tarefas de um usuário dentro de uma organização.

Herança de Funções: Uma característica poderosa do RBAC é a capacidade de criar hierarquias de funções, onde funções de nível superior herdam as permissões de funções de nível inferior. Isso simplifica a gestão de permissões, especialmente em organizações grandes e complexas.

Separação de Deveres: O RBAC suporta a separação de deveres, que é crucial para a segurança interna. Isso significa que o sistema pode ser configurado para evitar conflitos de interesse, garantindo que nenhuma pessoa tenha um conjunto de permissões que possa ser usado para comprometer ou abusar do sistema.

Flexibilidade e Escalabilidade: O RBAC é altamente flexível e escalável, tornando-o adequado para organizações de todos os tamanhos. Ele pode ser personalizado para atender às necessidades específicas de diferentes departamentos ou projetos dentro de uma organização.

Conformidade e Auditoria: O modelo facilita a conformidade com normas e regulamentações de segurança, pois oferece um controle claro sobre quem tem acesso a quais dados e sistemas. Além disso, facilita a auditoria de acessos e ações dentro do sistema.

Integração com Outros Sistemas: O RBAC pode ser integrado com outros sistemas e tecnologias, como sistemas de gerenciamento de identidades e federação de identidades, ampliando sua utilidade e eficácia.

Aplicações do RBAC:
Empresas e Organizações: Para gerenciar o acesso a sistemas de informações corporativos, incluindo recursos financeiros, recursos humanos e dados operacionais.
Sistemas de Saúde: Para controlar o acesso a registros médicos e outras informações sensíveis.
Governo e Instituições Públicas: Na gestão de permissões em sistemas governamentais que requerem altos níveis de segurança e controle de acesso.
O RBAC é reconhecido por sua capacidade de melhorar a segurança dos sistemas, simplificar a administração de permissões e aumentar a eficiência operacional, sendo por isso amplamente adotado em diversos setores.

Outros modelos de controle de acesso e gestão de permissões em sistemas de informação:

Discretionary Access Control (DAC):

Descrição: No DAC, o controle de acesso é baseado na identidade dos usuários e na decisão discricionária do proprietário do recurso (por exemplo, um arquivo). O proprietário decide quem pode acessar o recurso e quais operações podem ser realizadas.
Uso: Comum em sistemas operacionais e sistemas de arquivos onde os usuários têm a liberdade de controlar seus próprios recursos.

Mandatory Access Control (MAC):

Descrição: O MAC é um modelo mais rigoroso onde o acesso é controlado por um sistema centralizado, baseado em políticas de segurança estabelecidas pela organização. As permissões para acessar recursos são definidas com base em classificações de segurança tanto dos usuários quanto dos recursos.
Uso: Frequentemente usado em ambientes que exigem altos níveis de segurança, como instituições governamentais ou militares.

Attribute-Based Access Control (ABAC):

Descrição: No ABAC, o acesso é concedido não apenas com base no papel do usuário, mas também em um conjunto de atributos (como departamento, hora do dia, localização, etc.). Este modelo permite políticas de acesso mais dinâmicas e contextuais.
Uso: Útil em ambientes complexos e dinâmicos, como sistemas em nuvem e ambientes de TI corporativos.
Rule-Based Access Control (RB-RAC):

Descrição: Neste modelo, o acesso é baseado em um conjunto de regras definidas que determinam quem pode acessar o recurso. As regras podem ser baseadas em critérios como o tipo de recurso, a hora do dia, a localização do usuário, etc.
Uso: Comum em sistemas que necessitam de políticas de acesso flexíveis, mas ainda assim bem definidas.

Context-Based Access Control:

Descrição: Semelhante ao ABAC, mas com um foco mais forte no contexto da solicitação de acesso, como a localização do usuário, o dispositivo usado, a hora do dia e outros fatores ambientais.
Uso: Utilizado em sistemas que precisam de uma avaliação dinâmica do contexto para decidir sobre o acesso.
Organization-Based Access Control (OrBAC):
Descrição: O OrBAC abstrai a noção de roles para o nível organizacional, permitindo a definição de políticas de acesso em termos de atividades organizacionais, em vez de funções específicas de usuários.
Uso: Adequado para organizações grandes e complexas, onde as políticas de acesso precisam refletir a estrutura e os processos organizacionais.

Referencias: 
https://www.redhat.com/pt-br/topics/security/what-is-role-based-access-control

https://www.linkedin.com/pulse/o-que-%C3%A9-rbac-e-como-ele-pode-beneficiar-voc%C3%AA-sua-empresa-aldo-pereira/?originalSubdomain=pt

https://www.sailpoint.com/pt-br/identity-library/what-is-role-based-access-control/

https://help.alteryx.com/20214/pt/server/administer-alteryx-server/user-and-group-management/user-roles-and-permissions.html#idm46342204824896

**Comment by Felipeness** [comment]
Usei uma base mais de artigo para escrever, por isso ficou nesse formato, não sei se é o melhor formato

**Comment by Felipeness** [comment]
manda de novo

**Comment by Felipeness** [comment]
Eu quero!!!
