### ISSUE TITLE
Criar um middleware de autorização baseado nas roles

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#49]
Descreva a funcionalidade
Desenvolver um middleware de autorização baseado em funções (roles) utilizando uma biblioteca específica na linguagem de programação Go (Golang).

Necessario o estudo de biblioteca, falar com @Felipeness

Descrição
Esta funcionalidade propõe a criação de um middleware de autorização que se baseia nas funções (roles) atribuídas aos usuários. O objetivo é implementar um sistema robusto que permita restringir o acesso a determinadas rotas com base nas permissões específicas associadas às funções dos usuários. O uso de uma biblioteca especializada em Golang facilitará a implementação e manutenção desse middleware.

Cenário de Uso
O middleware de autorização baseado em funções é essencial para controlar o acesso a recursos sensíveis da aplicação. Isso possibilitará a definição clara de permissões, garantindo que apenas usuários com as funções apropriadas possam acessar determinadas rotas, contribuindo assim para a segurança e integridade do sistema.

Detalhes de Implementação
A implementação desse middleware envolve a escolha e integração de uma biblioteca específica para autorização baseada em funções. Após a seleção, será necessário configurar o middleware para avaliar as funções dos usuários e permitir ou negar o acesso de acordo com as permissões associadas.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
É crucial documentar as funções disponíveis, suas permissões associadas e como elas serão utilizadas no processo de autorização. Os desenvolvedores devem ser informados sobre como atribuir funções aos usuários e como configurar o middleware de autorização em suas rotas específicas.

**Comment by Lefel95** [comment]
21

**Comment by Clerijr** [comment]
eu quero!!!
