### ISSUE TITLE
Estudar Biblioteca de autenticação

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#50]
Descreva a funcionalidade
Realizar um estudo sobre bibliotecas de autenticação para posterior uso em middleware no contexto da linguagem de programação Go (Golang).

Descrição
Esta funcionalidade envolve uma investigação aprofundada das bibliotecas de autenticação disponíveis para a linguagem Go (Golang). O objetivo é identificar e compreender as melhores opções de bibliotecas que podem ser integradas como middleware para fortalecer a autenticação em rotas específicas de uma aplicação desenvolvida em Golang.

Cenário de Uso
O estudo das bibliotecas de autenticação é crucial para escolher uma solução eficiente e segura que atenda às necessidades específicas da aplicação em questão. O uso posterior dessas bibliotecas como middleware contribuirá para a implementação de um sistema robusto de autenticação, garantindo a proteção das rotas sensíveis.

Detalhes de Implementação
O processo de implementação inicia-se com a pesquisa e avaliação das bibliotecas de autenticação disponíveis para Golang. Após a seleção da biblioteca mais adequada, será necessário entender e seguir as práticas recomendadas para integrar a biblioteca como middleware nas rotas desejadas.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
É fundamental documentar as conclusões do estudo, destacando os critérios utilizados para a escolha da biblioteca. Além disso, os desenvolvedores envolvidos no projeto devem ser informados sobre as decisões tomadas e instruídos sobre como implementar e configurar o middleware de autenticação com a biblioteca escolhida.

**Comment by Lefel95** [comment]
13

**Comment by Felipeness** [comment]
Eu quero!!!
