### ISSUE TITLE
Fazer middleware de Autenticação

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#51]
Descreva a funcionalidade
Fazer e Implementar um middleware de autenticação utilizando uma biblioteca específica para garantir a segurança nas rotas que exigem autenticação.
A escolha da biblioteca esta a cargo do estudo e escolha do responsavel em conjunto do time

Descrição
Esta funcionalidade propõe a criação de um middleware de autenticação, integrando uma biblioteca especializada para reforçar a segurança em rotas que requerem autenticação. A utilização de uma biblioteca dedicada simplificará e padronizará o processo de autenticação, proporcionando uma solução robusta e eficiente.

Cenário de Uso
A implementação desse middleware é essencial para garantir que apenas usuários autenticados tenham acesso a determinadas rotas, especialmente aquelas que lidam com informações sensíveis, como a listagem completa de pets com links para as páginas das ONGs. Esse middleware contribuirá para a proteção dos dados e a integridade do sistema como um todo.

Detalhes de Implementação
A implementação do middleware de autenticação envolve a escolha e integração de uma biblioteca específica para tratamento de autenticação. Serão necessários ajustes nas rotas existentes para aplicar o middleware quando necessário, validando as credenciais do usuário antes de permitir o acesso às funcionalidades protegidas.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
A documentação para desenvolvedores deve ser atualizada para incluir informações sobre como utilizar e configurar o middleware de autenticação. Além disso, é recomendável realizar testes extensivos para garantir a eficácia e a segurança do sistema após a implementação dessa funcionalidade.

**Comment by Lefel95** [comment]
13
