### ISSUE TITLE
Sem autenticação a Pagina mostra 8 pets (sem link para pagina da ong)

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#53]
Descreva a funcionalidade
Implementação de rota de listagem de pets sem autenticação, exibindo até 8 pets sem links para a página da ONG.
As propriedades do pet sao: 
 - Foto
 - Nome
 - Raca
 - Genero
 - Idade

Descrição
A funcionalidade proposta visa oferecer uma visualização limitada da lista de pets para usuários não autenticados. Sem autenticação, a rota de listagem de pets apresentará até 8 animais, sendo que cada um não terá um link direto para a página da ONG responsável.

Cenário de Uso
Essa implementação proporciona uma prévia da variedade de pets disponíveis, promovendo o interesse dos usuários em se autenticarem para obter uma experiência mais completa, incluindo informações detalhadas sobre cada pet e links para as respectivas páginas das ONGs.

Detalhes de Implementação
A implementação dessa funcionalidade envolve a configuração da rota de listagem de pets, limitando a quantidade a ser exibida para usuários não autenticados. Será necessário ajustar a lógica de apresentação na interface, garantindo que os pets sejam mostrados de forma atrativa, mesmo sem links diretos para as páginas das ONGs.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
É fundamental considerar a usabilidade e a atratividade visual da lista de pets para incentivar a autenticação. A comunicação clara sobre a limitação da visualização sem autenticação também é crucial para orientar os usuários sobre os benefícios de se autenticarem na plataforma.

**Comment by Lefel95** [comment]
8

**Comment by hxsggsz** [comment]
eu quero!!!

![284573435-e6b89e7e-f804-45bf-8e93-030162c13a7e](https://github.com/devhatt/pet-dex-backend/assets/103784814/95b37e82-74fe-43ef-a5e0-5be285a361b3)

**Comment by RenanppCosta** [comment]
Eu quero!!!

**Comment by devlefel** [comment]
Duplicada
