### ISSUE TITLE
Fazer rota de listagem de pets ter autenticacao e listagem diferenciada para usuarios nao autenticados

### ISSUE THREAD

**Issue by GabrielTrindadeC** [devhatt/pet-dex-backend#54]
Descreva a funcionalidade
Implementação de rota de listagem de pet com autenticação, onde a visualização sem autenticação exibirá apenas 8 animais sem links, enquanto a visualização autenticada apresentará todos os animais com links para as respectivas páginas dos animais.
As propriedades do pet sao:
    - Foto
    - Nome
    - Raca
    - Genero
    - Idade

Descrição
A funcionalidade proposta visa aprimorar a segurança e controle de acesso à listagem de animais das ONGs. Sem autenticação, os usuários terão acesso a uma visualização limitada, exibindo até seis animais sem links associados. Ao autenticar-se, os usuários terão permissão para visualizar a lista completa de animais, cada um com um link direto para a página específica do animal.

Cenário de Uso
Esta funcionalidade beneficia o projeto ao oferecer uma camada adicional de segurança e personalização da experiência do usuário. A restrição de acesso sem autenticação visa proteger informações sensíveis, enquanto a visualização completa com links proporciona uma experiência mais rica e interativa para os usuários autenticados.

Detalhes de Implementação
A implementação dessa funcionalidade pode envolver a integração de um sistema de autenticação, como JWT, Oauth por exemplo e a configuração de rotas condicionais para lidar com diferentes níveis de acesso. Além disso, será necessário desenvolver a lógica de exibição dos animais, limitando a quantidade e a presença de links com base no status de autenticação do usuário.

Conceitos Visuais
[Incluir qualquer esboço ou representação visual, se aplicável.]

Informações Adicionais
É importante considerar a experiência do usuário ao implementar essa funcionalidade, garantindo que a transição entre as visualizações autenticada e não autenticada seja intuitiva e compreensível. Além disso, a documentação para os desenvolvedores e usuários finais deve ser atualizada para refletir essas alterações.

**Comment by Lefel95** [comment]
21

**Comment by marcos-ab-nolasco** [comment]
Eu quero!

**Comment by marcos-ab-nolasco** [comment]
Eu queroo!!!

**Comment by luanc202** [comment]
Eu quero!!!
