### ISSUE TITLE
[UPDATE PET] Incluir campo propriedade Aniversario e Dia de doacao no endpoint de Update Pet

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#56]
**Descreva a funcionalidade**
Atualizar o endpoint de atualizar informações de um animal (Pet), permitindo que as propriedades "Aniversário" e "Dia de Doação" sejam recebidas e atualizadas.
Atualizar os campos que nao existem no banco via migrations

**Descrição**
Essa funcionalidade tem como objetivo possibilitar que os usuários atualizem as informações relacionadas às datas importantes de um animal, como seu aniversário e o dia em que foi adotado (Dia de Doação). Isso permite manter registros precisos e significativos sobre a história do animal.

**Cenário de Uso**
A inclusão da capacidade de atualizar as propriedades "Aniversário" e "Dia de Doação" é útil quando os usuários desejam manter informações detalhadas sobre os eventos significativos na vida do animal.

**Detalhes de Implementação**
A implementação envolve a expansão do endpoint de atualização de pets para aceitar uma requisição que inclua as novas datas. A lógica no backend deve validar e processar a requisição, atualizando as propriedades "Aniversário" e "Dia de Doação" do animal no banco de dados.

**Exemplo de Requisição**
```json
PATCH /api/pets/{id}
{
  "aniversario": "2023-05-15",
  "dia_doacao": "2023-08-01"
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint deve ser atualizada para refletir essa nova capacidade, e os desenvolvedores e usuários finais devem ser informados sobre a existência e uso desse recurso. Testes abrangentes devem ser realizados para garantir o correto funcionamento do endpoint de atualização do pet com a inclusão das novas propriedades.

**Comment by AtilaRocha** [comment]
EU QUERO!!!

**Comment by Lefel95** [comment]
8

**Comment by yuri-silveiraa** [comment]
eu quero!!!
