### ISSUE TITLE
[UPDATE PET] Incluir campo de Castrado no endpoint de Update Pet

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#57]
**Descreva a funcionalidade**
Atualizar o endpoint de atualizar informações de um animal (Pet), permitindo que a propriedade "Castrado" (boolean) seja recebida e atualizada.

Adicionar campos faltantes no banco via migration

**Descrição**
Essa funcionalidade busca possibilitar que os usuários atualizem a informação sobre se um animal é castrado ou não por meio de um endpoint específico. Isso oferece uma maneira direta de manter registros precisos sobre o estado de castração de cada animal.

**Cenário de Uso**
A inclusão da capacidade de atualizar a propriedade "Castrado" é útil quando os usuários desejam registrar ou modificar o status de castração de um animal no sistema.

**Detalhes de Implementação**
A implementação envolve a expansão do endpoint de atualização de pets para aceitar uma requisição que inclua o novo valor para a propriedade "Castrado". A lógica no backend deve validar e processar a requisição, atualizando o status de castração do animal no banco de dados.

**Exemplo de Requisição**
```json
PATCH /api/pets/{id}
{
  "castrado": true
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint deve ser atualizada para refletir essa nova capacidade, e os desenvolvedores e usuários finais devem ser informados sobre a existência e uso desse recurso. Testes abrangentes devem ser realizados para garantir o correto funcionamento do endpoint de atualização do pet com a inclusão da propriedade "Castrado".

**Comment by jykon** [comment]
EU QUERO!!!

**Comment by Lefel95** [comment]
5

**Comment by felipelaraujo** [comment]
EU QUERO!!!

**Comment by andresavasconcelos** [comment]
Eu queroo!!!
