### ISSUE TITLE
[UPDATE PET] Incluir campo de Cuidados especiais (Sim ou nao e descricao)

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#58]
**Descreva a funcionalidade**
Atualizar o endpoint de update (Pet), permitindo que a propriedade "Cuidados Especiais" seja recebida e atualizada, incluindo um campo booleano "Sim ou Não" e uma descrição associada.

Adicionar os campos faltantes no banco via migrations

**Descrição**
Essa funcionalidade visa oferecer aos usuários a capacidade de atualizar informações sobre cuidados especiais necessários para um animal. Com um campo booleano indicando se são necessários cuidados especiais e uma descrição associada, os usuários podem comunicar detalhes específicos sobre esses cuidados.

**Cenário de Uso**
A inclusão da propriedade "Cuidados Especiais" é útil quando os usuários precisam compartilhar informações importantes sobre os cuidados específicos que um animal pode precisar.

**Detalhes de Implementação**
A implementação envolve a expansão do endpoint de atualização de pets para aceitar uma requisição que inclua os novos valores para a propriedade "Cuidados Especiais". A lógica no backend deve validar e processar a requisição, atualizando a indicação e a descrição de cuidados especiais do animal no banco de dados.

**Exemplo de Requisição**
```json
PATCH /api/pets/{id}
{
  "cuidados_especiais": {
    "necessario": true,
    "descricao": "Requer medicação diária"
  }
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint deve ser atualizada para refletir essa nova capacidade, e os desenvolvedores e usuários finais devem ser informados sobre a existência e uso desse recurso. Testes abrangentes devem ser realizados para garantir o correto funcionamento do endpoint de atualização do pet com a inclusão da propriedade "Cuidados Especiais".

**Comment by Lefel95** [comment]
5

**Comment by mmaysc** [comment]
eu quero!!!
