### ISSUE TITLE
[UPDATE PET] Incluir campo de Vacinas (array de vacina tipo, data e nome do doutor)

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#59]
**Descreva a funcionalidade**
Atualizar o endpoint de Update PET, permitindo que a propriedade "Vacinas" seja recebida e atualizada como um array de objetos contendo tipo de vacina, data de aplicação e nome do médico responsável.
Atualizar Banco de dados com as propriedades, via migrations.

**Descrição**
Essa funcionalidade tem como objetivo oferecer aos usuários a capacidade de manter registros detalhados sobre as vacinas aplicadas a um animal. Ao enviar um array contendo informações sobre tipo de vacina, data de aplicação e nome do médico responsável, os usuários podem manter um histórico preciso de imunizações.

**Cenário de Uso**
A inclusão da propriedade "Vacinas" é útil quando os usuários desejam registrar e manter um histórico completo das vacinações realizadas em um animal, proporcionando uma visão abrangente sobre a saúde do pet.

**Detalhes de Implementação**
A implementação envolve a expansão do endpoint de atualização de pets para aceitar uma requisição que inclua os novos valores para a propriedade "Vacinas". A lógica no backend deve validar e processar a requisição, atualizando o histórico de vacinas do animal no banco de dados.

**Exemplo de Requisição**
```json
PATCH /api/pets/{id}
{
  "vacinas": [
    {
      "tipo": "V8",
      "data_aplicacao": "2023-03-01",
      "nome_doutor": "Dr. Veterinário"
    },
    {
      "tipo": "Antirrábica",
      "data_aplicacao": "2023-05-15",
      "nome_doutor": "Dr. Vet"
    }
  ]
}
```

**Conceitos Visuais**
[Incluir qualquer esboço ou representação visual, se aplicável.]

**Informações Adicionais**
A documentação do endpoint deve ser atualizada para refletir essa nova capacidade, e os desenvolvedores e usuários finais devem ser informados sobre a existência e uso desse recurso. Testes abrangentes devem ser realizados para garantir o correto funcionamento do endpoint de atualização do pet com a inclusão da propriedade "Vacinas".

**Comment by joaovaladares** [comment]
EU QUERO!!!

**Comment by iasarchi** [comment]
EU QUERO!!!
