### ISSUE TITLE
Refatorar a feature de FindByID do Pet

### ISSUE THREAD

**Issue by devlefel** [devhatt/pet-dex-backend#94]
**Describe the feature**
Atualmente a Feature de findById do Petdex esta em um controller errado, e nao esta usando nossos padroes de projeto. Precisamos refatorala

<details open>
  <summary>
    <b>Precisamos Alterar o controller para o pet controller</b>
  </summary>
</details>

<br>

<details> 
  <summary>
    <b>Precisamos Adicionar testes</b>
  </summary>
 
</details>

<br>

<details> 
  <summary>
    <b>Precisamos adicionar UUID</b>
  </summary>
</details>

<br>

<details> 
  <summary>
    <b>Implementation Details</b>
  </summary>

</details>

<br>

<details> 
  <summary>
    <b>Visual Concepts</b>
  </summary>

[Include any visual representations or concepts if those are available and applicable.]

</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>
  
[Provide any additional information, such as context that might be relevant to the implementation of this specific feature.]
</details>

**Comment by davidspader** [comment]
EU QUERO!!!
